import json
from pathlib import Path
here=Path(__file__).resolve().parent
prompts=json.loads((here.parent/'shared/prompts.json').read_text())
steps=[('frame',[],['round-request.md']),('discover',[('round-request.md','single')],['batch.md','source-request-*.md','empty.md']),('read',[('source-request-*.md','each')],['assessment.md']),('synthesize',[('batch.md','single'),('assessment*.md','complete')],['synthesis.md']),('decide',[('synthesis.md','single')],['round-request.md','review.md']),('finish-empty',[('empty.md','single')],['review.md'])]
lines=['+++','version = 2','key = "matched-literature-review"','title = "Matched Literature Review"','description = "Discover, read each new source, synthesize, and repeat while useful gaps remain."','default_model = ""','default_harness = "omp"']
for key,inputs,outputs in steps:
 lines += ['', '[[step]]',f'key = "{key}"',f'title = "{key.replace("-"," ").title()}"',f'short = "{key}"','inputs = ['+', '.join('{ path = '+json.dumps(x)+', mode = '+json.dumps(y)+' }' for x,y in inputs)+']','outputs = ['+', '.join('{ path = '+json.dumps(x)+' }' for x in outputs)+']','model = ""','harness = ""','is_coding_step = false','auto_advance_default = true']
lines += ['+++','','# Matched Literature Review','','Generated from the shared operation prompts and the mappings in build_playbook.py. Each agent writes only its assigned publication. The engine creates every successor session.']
contract='''Read exactly the input paths in the engine assignment block. Logical names below are roles, not physical filenames. Write only to corresponding assigned paths under {{ARTIFACTS_DIR}}, expanding a wildcard only in its assigned position. Do not scan for the newest file or overwrite prior publications. Do not create downstream sessions. After all selected outputs are complete, request the supplied completion operation and finish; the engine waits for the completed handoff. Honor any completion lock and never self-authorize.

Structured artifact files contain a single JSON object (ordinary UTF-8 text despite the .md suffix). State fields are question, scope, round, queries, seen, assessments and synthesis. Round starts at 1; queries/seen are string arrays; assessments is an array of source assessments; synthesis is cumulative Markdown. Source fields are id, url and title. Assessment adds summary, limitations and citations (URL strings). No field may silently discard earlier evidence. Use exact trimmed URLs for duplicate detection.

'''
mapping={
'frame':'''Your input question is the original ticket at {{TICKET_FILE}}. Write the returned initial State to round-request.md. Run only once; later round-request.md publications must not restart framing.''',
'discover':'''Read round-request.md as state. Return {sources, notes}. Remove empty trimmed URLs, duplicate trimmed URLs and URLs already in state.seen before publication. If any new sources remain, write batch.md = {state, discovery:{sources,notes}}, then one source-request-NNN.md = {state,source} per source, with NNN = 001, 002, ... within this assigned family. If no sources remain, write only empty.md = {state,notes}. Never publish both routes. Do not publish a batch with zero source requests. Each request must retain the full state for its reader.''',
'read':'''The single assigned source-request member already contains {state,source}. Write the returned Assessment to assessment.md. Every dispatched reader must publish one honest assessment, including when its source is inaccessible. A crashed or failed reader must not be treated as an empty successful assessment.''',
'synthesize':'''Read {state,discovery} from batch.md and every assessment in the one engine-supplied complete collection. Never substitute an assessment from another round. Check exactly one assessment per discovery source and preserve the source identities. Produce {text,gaps,queries}; then construct an updated State: keep question/scope/round/queries, append all current source URLs to seen and all current assessments to assessments, and set synthesis=text. Write synthesis.md = {state:updatedState,synthesis:{text,gaps,queries}}. Do not advance the round here.''',
'decide':'''Read synthesis.md as {state,synthesis}. Produce {continue,queries,reason,report}. If continue=true, require nonempty queries; write only round-request.md with question/scope/seen/assessments/synthesis preserved, round increased by one, and queries replaced. If continue=false, write only review.md containing the complete Markdown report. Never publish both a new round and a final report. Branch exclusivity is an agent obligation, not an XOR feature of the engine.''',
'finish-empty':'''Read empty.md as {state,notes}. Write only review.md with the report string as Markdown. No reader, synthesis or decision invocation is needed for this empty batch.'''}
for key,_,_ in steps:
 lines += ['',f'<!-- alinery:step {key} -->','',contract+prompts[key.replace('-','_')], '',mapping[key],'','Additional user instructions: {{PROMPT_EXTRA}}']
(here/'playbook.md').write_text('\n'.join(lines)+'\n')
